name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - tadmccorkle
body:
  - type: markdown
    attributes:
      value: Please fill out all relevant inputs to make fixing the bug as easy as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened, and what did you expect to happen instead?
      placeholder: A description of the bug...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce...
      description: How can the behavior be reproduced?
      placeholder: |
        1. Set up configuration '...'
        2. Run '...'
        3. See error
    validations:
      required: false
  - type: dropdown
    id: affected-libraries
    attributes:
      label: Affected libraries
      description: Which libraries does this bug affect?
      options:
        - Gtri.Rpc
        - Gtri.Rpc.RabbitMQ
        - Gtri.Rpc.JsonRpc
      multiple: true
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else you'd like to mention? Stack trace, other comments, etc.?
      placeholder: Add additional context here...
    validations:
      required: false
